version: "3"
services:
  web:
    build: ./backend/golang_web/
    restart: always
    networks:
      webapp:
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    build: .
    restart: always
    networks:
      webapp:
    ports:
      - "3306:3306"
    volumes:
      - ~/blog/mysql/data:/var/lib/mysql

  nginx:
    image: nginx
    restart: always
    networks:
      webapp:
    ports:
      - "80:80"
    volumes:
      - ~/blog/nginx/html/:/usr/share/nginx/html/
      - ~/blog/nginx/conf/nginx.conf:/etc/nginx/nginx.conf

networks:
  webapp:
    driver: bridge
